/*
 * generated by Xtext 2.10.0
 */
package uniandes.automat.sql.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SqlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uniandes/automat/sql/parser/antlr/internal/InternalSql.tokens");
	}
}
