/*
 * generated by Xtext 2.10.0
 */
package uniandes.automat.sql.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSqlScopeProvider extends DelegatingScopeProvider {
}
